@hostAddress = https://localhost:7055

POST {{hostAddress}}/api/courses
Content-Type: application/json

{
  "title": "Testing Duration In Minutes",
  "description": "Duration in minutes test description",
  "durationInMinutes": 180
}

###

GET {{hostAddress}}/api/courses/0bc6e20e-01e3-46e4-ba39-a61c2b8035ff
Accept: application/json

###