@hostAddress = https://localhost:7055

POST {{hostAddress}}/api/courses
Content-Type: application/json

{
  "title": "Intro to C#",
  "description": "Learn the basics of C#."
}

###

GET {{hostAddress}}/api/courses/E1DCB1CB-97EA-4A7A-A63A-C6B713C5270F
Accept: application/json

###